services:
  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
    restart: always
    labels:
      caddy: ${PORTAINER_DOMAIN}
      caddy.reverse_proxy: "{{upstreams 9000}}"
    networks:
      - caddy

volumes:
  portainer_data:

networks:
  caddy:
    external: true
